{{- if eq .Values.ingress.ingressClassName "openbalena-haproxy" }}
{{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
apiVersion: networking.k8s.io/v1
{{- else if .Capabilities.APIVersions.Has "networking.k8s.io/v1beta1/Ingress" }}
apiVersion: networking.k8s.io/v1beta1
{{- else }}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ include "openbalena.fullname" . }}-tunnel
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openbalena.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    ingress.kubernetes.io/ssl-passthrough: "true"
    {{- with .Values.ingress.tunnel.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  tls:
  - hosts:
    - tunnel.{{ .Values.global.hostname }}
    secretName: {{ include "openbalena.fullname" . }}-tunnel-tls
  rules:
  - host: tunnel.{{ .Values.global.hostname }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "openbalena.fullname" . }}-internal-tunnel
            port:
              number: 3128

{{- else if eq .Values.ingress.ingressClassName "traefik" }}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: {{ include "openbalena.fullname" . }}-tunnel
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openbalena.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.ingress.http.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.ingress.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  entryPoints:
  - websecure
  routes:
  - match: HostSNI(`tunnel.{{ .Values.global.hostname }}`)
    services:
    - name: {{ include "openbalena.fullname" . }}-vpn
      port: 3128
  tls:
    passthrough: true
{{- end }}